apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api-app
  template:
    metadata:
      labels:
        app: web-api-app
    spec:
      containers:
      - name: web-api-app
        image: <your-docker-image>
        ports:
        - containerPort: 3000
